image: docker:git
services:
  - docker:dind
  
before_script:
  - apk update && apk add --no-cache docker
    python3-dev py3-pip docker gcc git curl build-base
    autoconf automake py3-cryptography linux-headers
    musl-dev libffi-dev openssl-dev openssh rsync
  - pip3 install ansible molecule docker

test:role:
  stage: test
  script:
    - mkdir -p /stage/docker-registry
    - molecule converge
  tags:
    - docker

after_script:
   - molecule destroy 