# -*- mode: ruby -*-
# vi: set ft=ruby :
Vagrant.configure("2") do |config|
  config.vm.box = "bento/centos-7.3"

  config.vm.define "web" do |web|
    web.vm.hostname = "apache"
    web.vm.network "private_network", ip: "192.168.33.20"
  end
  config.vm.define "db" do |db|
    db.vm.hostname = "mysql"
    db.vm.network "private_network", ip: "192.168.33.30"
  end
end
