version: '3'
services:

  registry:
     image: registry:2
     restart: unless-stopped
     container_name: registry
     ports:
        - "5000:5000"
     #Setting Up Authentication and TLS certificate
     #environment:
        #REGISTRY_HTTP_TLS_CERTIFICATE: /certs/domain.crt
        #REGISTRY_HTTP_TLS_KEY: /certs/domain.key
        #REGISTRY_AUTH: htpasswd
        #REGISTRY_AUTH_HTPASSWD_PATH: /auth/htpasswd
        #REGISTRY_AUTH_HTPASSWD_REALM: Registry Realm
     volumes:
        - /var/local/docker/registry:/var/lib/registry
        #- /path/certs:/certs
        #- /path/auth:/auth

  docker-registry-ui:
     image: konradkleine/docker-registry-frontend:v2
     container_name: docker-registry-ui
     ports:
       - "8080:80"
     environment:
       ENV_DOCKER_REGISTRY_HOST: registry
       ENV_DOCKER_REGISTRY_PORT: 5000
