---
  - name: Remove swapfile from /etc/fstab.
    mount:
      name: "{{ item }}"
      fstype: swap
      state: absent
      with_items:
        - swap
        - none
  - name: Disable swap.
    command: swapoff -a
    when: ansible_swaptotal_mb > 0

  - name: Add an apt signing key for Kubernetes.
    apt_key:
      url: {{ k8s_key_path }}
      state: present

  - name: Add Adding apt repository for Kubernetes.
    apt_repository:
      repo: {{ k8s_download_path }}
      state: present
      filename: kubernetes.list

  - name: Install Kubernetes binaries.
    apt:
      name: "{{ packages }}"
      state: present
      update_cache: yes
    vars:
      packages:
        - kubelet
        - kubeadm
        - kubectl

  - name: Download Kubectl binaries.
    get_url:
      url: {{ kubectl_download_path }}
      dest: /usr/local/bin
      owner: root
      group: root
      mode: '0755'
      force: yes

  - name: Configure node ip
    lineinfile:
      path: /etc/default/kubelet
      line: KUBELET_EXTRA_ARGS=--node-ip={{ node_ip }}

  - name: Restart kubelet
    service:
      name: kubelet
      daemon_reload: yes
      state: restarted

  - name: Initialize the Kubernetes cluster using kubeadm.
    command: kubeadm init --apiserver-advertise-address="{{ apiserver_address }}" --apiserver-cert-extra-sans="{{ apiserver_address }}"  --node-name "{{ master_name }}" --pod-network-cidr="{{ network_cidr }}"

 - name: Install calico pod network.
   command: kubectl create -f "{{ calico_network_path }}"

 - name: Generate join command.
   command: kubeadm token create --print-join-command
   register: join_command

  - name: Copy join command to local file.
    local_action: copy content="{{ join_command.stdout_lines[0] }}" dest="./join-command"
